#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Nov  6 14:33:37 2017

@author: goel
"""
import os
import sys
import pandas as pd
from func.synsearchFunctions import readSVData, getSV, getNotAligned

if __name__ == "__main__":
    if len(sys.argv) == 1:
        print("Using", os.getcwd(), "as working directory")
    if len(sys.argv) == 2:
        try:
            os.chdir(sys.argv[1])
        except:
            sys.exit("Error in setting", sys.argv[1], "as the working directory")
    cwdPath = os.getcwd()+ os.sep
    listDir = os.listdir()
    fileLists = ["synOut.txt","invOut.txt", "TLOut.txt", "invTLOut.txt","ctxOut.txt"]
    for file in fileLists:
        if file not in listDir:
            sys.exit(file + "is not present in the directory. Exiting")
    
    allAlignments = readSVData(cwdPath)
    mumSNPIn = allAlignments[["aStart","aEnd","bStart","bEnd","aChr","bChr"]].copy()
    mumSNPIn.to_csv(cwdPath+"mumSNPIn.txt",sep="\t",header = False, index = False)
    getSV(cwdPath, allAlignments)
    
    getNotAligned(cwdPath)
