#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Nov  6 14:33:37 2017

@author: goel
"""


import argparse 
import os
import sys

if __name__ == "__main__":

    
    parser = argparse.ArgumentParser()
    parser.add_argument('-d','--dir',help="path to working directory (in not current directory)", action = 'store', default = os.getcwd()+os.sep)
    parser.add_argument("-p","--prefix", help="Prefix for filenames", type = str, default = "")
    args = parser.parse_args()
    
    cwdPath = args.dir + os.sep
    prefix = args.prefix
    
    listDir = os.listdir(cwdPath)
    fileLists = ["synOut.txt","invOut.txt", "TLOut.txt", "invTLOut.txt","ctxOut.txt"]
    for file in fileLists:
        if prefix+file not in listDir:
            sys.exit(file + " is not present in the directory. Exiting")
        
    from pyxFiles.synsearchFunctions import readSVData, getSV, getNotAligned
    allAlignments = readSVData(cwdPath, prefix)
    mumSNPIn = allAlignments[["aStart","aEnd","bStart","bEnd","aChr","bChr"]].copy()
    mumSNPIn.to_csv(cwdPath+prefix+"mumSNPIn.txt",sep="\t",header = False, index = False)
    getSV(cwdPath, allAlignments, prefix)
    getNotAligned(cwdPath, prefix)
    