{% set version = "1.5.2" %}
{% set sha256 = "b87705421a2249fd5bb359642494a7f7a9bcbf90a0b73531d1da2d7fedbad396" %}

package:
  name: syri
  version: {{ version }}

source:
  url: https://github.com/schneebergerlab/syri/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python  >=3.8,<=3.10
    - setuptools
    - numpy   >=1.21.2
    - cython
  run:
    - python  >=3.8,<=3.10
    - numpy   >=1.21
    - pandas  >=1.2.4
    - scipy   >=1.6.2
    - psutil  >=5.8
    - python-igraph >=0.9.1
    - pysam
    - longestrunsubsequence
    - pulp

test:
  commands:
    - syri --version
    - chroder --version

about:
  home: https://github.com/schneebergerlab/syri
  license: MIT License
  license_file: LICENSE
  summary: Synteny and rearrangement identifier between whole-genome assemblies

extra:
  maintainers:
    - Manish Goel <goel@mpipz.mpg.de>

