# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# bioconda-utils is not installable via conda, and don't wanna bother installing something manually
#jobs:
#  bioconda-build:
#
#    runs-on: ubuntu-latest
#    strategy:
#      fail-fast: false
#      matrix:
#        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]
#
#    steps:
#    - uses: conda-incubator/setup-miniconda@v3
#      with:
#        auto-update-conda: true
#        python-version: ${{ matrix.python-version }}
#    - uses: actions/checkout@v4
#    - name: Install bioconda
#      run: |
#        conda install --channel bioconda bioconda::bioconda-utils
#    - name: Run bioconda lint
#      run: |
#        bioconda-utils lint
#    - name: Build recipe using bioconda
#      run: |
#        bioconda-utils build
